### ISSUE TITLE
Impossible to push schema changes due to ER_DROP_INDEX_FK

### ISSUE THREAD

**Issue by AlessioDP** [drizzle-team/drizzle-kit-mirror#124]
I am using `drizzle-kit@0.19.5`, `drizzle-orm@0.27.2` and `mysql2`.

When you create some tables with foreign keys:
```typescript
export const guildMemberTeams = mysqlTable('guild_members_teams', {
    id: int('id').autoincrement().notNull().primaryKey(),
    guildMemberId: int('guild_member_id').references(() => guildMembers.id),
    // ...
});
export const guildMemberTeamsRelations = relations(guildMemberTeams, ({ one }) => ({
    guildMember: one(guildMembers, {
        fields: [guildMemberTeams.guildMemberId],
        references: [guildMembers.id]
    }),
}));
```

A SQL code like this is created:
```mysql
CREATE TABLE `guild_members_teams` (
	`id` int AUTO_INCREMENT PRIMARY KEY NOT NULL,
	`guild_member_id` int,
	-- ....
);
-- ...
ALTER TABLE `guild_members_teams` ADD CONSTRAINT `guild_members_teams_guild_member_id_guild_members_id_fk` FOREIGN KEY (`guild_member_id`) REFERENCES `guild_members`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
```

As database empty, I usually execute `drizzle-kit push:mysql` to push and everything works fine.

But if you execute again `drizzle-kit push:mysql`, to push new schema changes to the database, I receive this error:
```
Error: Cannot drop index 'guild_members_guild_id_guilds_id_fk': needed in a foreign key constraint
    at PromiseConnection.query (...\node_modules\drizzle-kit\index.cjs:35205:26)
    at Command.<anonymous> (...\node_modules\drizzle-kit\index.cjs:52689:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_DROP_INDEX_FK',
  errno: 1553,
  sql: 'DROP INDEX `guild_members_guild_id_guilds_id_fk` ON `guild_members`;',
  sqlState: 'HY000',
  sqlMessage: "Cannot drop index 'guild_members_guild_id_guilds_id_fk': needed in a foreign key constraint"
}
```

**Comment by cdebotton** [comment]
I just wanted to add that I get this same error for unique indices, and it seems to happen with drizzle-kit 0.19.4 and 0.19.5 but it works as expected with 0.19.3.

```
pnpm db:push

> cdb-is-svelte2@0.0.1 db:push /Users/christian/www/cdb-is-svelte2
> drizzle-kit push:mysql --config=drizzle.config.ts

drizzle-kit: v0.19.5
drizzle-orm: v0.27.2

Reading config file '/Users/christian/www/cdb-is-svelte2/drizzle.config.ts'
Reading schema files:
/Users/christian/www/cdb-is-svelte2/src/lib/db/schema.ts

Error: target: cdb-is.-.primary: vttablet: rpc error: code = Unknown desc = Check constraint 'sessions__sessionToken__idx' is not found in the table. (errno 3821) (sqlstate HY000) (CallerID: 9f8lwu7cfrz3ol4n3kjl): Sql: "alter table sessions drop check sessions__sessionToken__idx", BindVars: {REDACTED}
    at PromiseConnection.query (/Users/christian/www/cdb-is-svelte2/node_modules/.pnpm/drizzle-kit@0.19.5/node_modules/drizzle-kit/index.cjs:35205:26)
    at Command.<anonymous> (/Users/christian/www/cdb-is-svelte2/node_modules/.pnpm/drizzle-kit@0.19.5/node_modules/drizzle-kit/index.cjs:52689:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: undefined,
  errno: 3821,
  sql: 'ALTER TABLE `sessions` DROP CONSTRAINT `sessions__sessionToken__idx`;',
  sqlState: 'HY000',
  sqlMessage: `target: cdb-is.-.primary: vttablet: rpc error: code = Unknown desc = Check constraint 'sessions__sessionToken__idx' is not found in the table. (errno 3821) (sqlstate HY000) (CallerID: 9f8lwu7cfrz3ol4n3kjl): Sql: "alter table sessions drop check sessions__sessionToken__idx", BindVars: {REDACTED}`
}
```

**Comment by steve-taylor** [comment]
@cdebotton I had the same issue and worked around it by using `unique` instead of `uniqueIndex`. Both of them produce a `UNIQUE KEY` in MySQL.

**Comment by AndriiSherman** [comment]
Was fixed in `drizzle-kit@mysql-uniques`. Could you please check? 
If that works for you - will release to latest today 

The problem was with unique constraints. In MySQL, there is no difference between them. Therefore, the logic was changed to treat MySQL unique indexes the same as unique constraints for diffs. The same was done for SQLite, but it was my mistake to overlook it in the MySQL handlers.

**Comment by AlessioDP** [comment]
I installed with yarn `drizzle-kit@mysql-uniques` (`0.19.5-0b8d69c`) and the generated query is the same, same error.

**Comment by steve-taylor** [comment]
@AndriiSherman I tried it and there's a new error:

```
drizzle-kit: v0.19.5
drizzle-orm: v0.27.2

Reading schema files:
/Users/steve/GITHUB/myorg/myapp/src/db/schema.ts

Error: target: mydatabase.-.primary: vttablet: rpc error: code = FailedPrecondition desc = Can't DROP 'PRIMARY'; check that column/key exists (errno 1091) (sqlstate 42000) (CallerID: someusername): Sql: "alter table practice_doctor drop primary key", BindVars: {REDACTED}
    at PromiseConnection.query (/Users/steve/GITHUB/myorg/myapp/node_modules/drizzle-kit/index.cjs:35236:26)
    at Command.<anonymous> (/Users/steve/GITHUB/myorg/myapp/node_modules/drizzle-kit/index.cjs:52720:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_CANT_DROP_FIELD_OR_KEY',
  errno: 1091,
  sql: 'ALTER TABLE `practice_doctor` DROP PRIMARY KEY;',
  sqlState: '42000',
  sqlMessage: `target: mydatabase.-.primary: vttablet: rpc error: code = FailedPrecondition desc = Can't DROP 'PRIMARY'; check that column/key exists (errno 1091) (sqlstate 42000) (CallerID: someusername): Sql: "alter table practice_doctor drop primary key", BindVars: {REDACTED}`
}
```

Here's the table definition in my drizzle schema:

```ts
export const practiceDoctors = mysqlTable(
    'practice_doctor',
    {
        practiceId: uuid('practice_id').notNull(), // references practices.id
        doctorId: uuid('doctor_id').notNull(), // references doctors.id
        healthengineDoctorId: text('healthengine_doctor_id'),
        hotdocDoctorSlug: text('hotdoc_doctor_slug')
    },
    ({practiceId, doctorId}) => ({
        idx1: unique('idx_practice_doctor_1').on(practiceId, doctorId)
    })
)
```

As you can see, it has no primary key. Maybe it should, but this isn't a problem in 0.19.5.

**Comment by AndriiSherman** [comment]
Checking that as well

**Comment by steve-taylor** [comment]
@AndriiSherman never mind - I think this issue was already there. If I `push` after no changes, even on 0.19.5, that error appears.

**Comment by AndriiSherman** [comment]
I’ll use your table schema to test it. Will update here

**Comment by steve-taylor** [comment]
I have a workaround: I removed the `unque` constraint and added this instead:

```ts
export const practiceDoctorsPrimaryKey = primaryKey(
    practiceDoctors.practiceId,
    practiceDoctors.doctorId
)
```

So it's an entirely different issue (i.e. `drizzle-kit` assumes all tables have a primary key) with a simple workaround in this case.

**Comment by AndriiSherman** [comment]
I’ll fix it in the same release. You helped me a lot. I guess I know where the issue is. Should be fast

**Comment by AndriiSherman** [comment]
I found an issue. It seems that the information schema drizzle-kit was examining marked those columns as unique and primary keys. This occurred because both columns have the properties of being unique and not null. However, I have found another source that can provide a better understanding of whether they are indeed primary keys. I will make changes to this part and will notify you with a new tag for you to check

**Comment by AndriiSherman** [comment]
@steve-taylor Just updated `drizzle-kit@mysql-uniques` with primary key fixes.

The issue was with incorrect querying of the information schema. Drizzle Kit was examining the column definition and the `column_key` setting from the `information_schema.columns table`. However, it turns out that the `column_key` value can indicate `PRIMARY` even for columns that are both `UNIQUE` and `NOT_NULL`, leading to a logical misinterpretation.

I have made changes to address this problem by utilizing the `information_schema.table_constraints` table, which provides a proper distinction between `primary keys` and columns with the combination of `UNIQUE` and `NOT_NULL`

Would be great if you can reinstall this tag and try with previous schema(before making unique as primary as workaround)
Going to make more tests, but seems like this should work great

**Comment by AndriiSherman** [comment]
I released it in `drizzle-kit@0.19.6`. Please close this issue if it fixes your problem

**Comment by AlessioDP** [comment]
I still have the original issue, this is what exactly I am testing:
```typescript
export const guildMembers = mysqlTable('guild_members', {
    id: int('id').autoincrement().notNull().primaryKey(),
    name: varchar('name', { length: 256 }).notNull(),
});
export const guildMemberTeams = mysqlTable('guild_members_teams', {
    id: int('id').autoincrement().notNull().primaryKey(),
    guildMemberId: int('guild_member_id').references(() => guildMembers.id),
});
export const guildMemberTeamsRelations = relations(guildMemberTeams, ({ one }) => ({
    guildMember: one(guildMembers, {
        fields: [guildMemberTeams.guildMemberId],
        references: [guildMembers.id]
    }),
}));
```

Error:
```txt
Error: Cannot drop index 'guild_members_teams_guild_member_id_guild_members_id_fk': needed in a foreign key constraint
    at PromiseConnection.query (....\node_modules\drizzle-kit\index.cjs:35267:26)
    at Command.<anonymous> (...\node_modules\drizzle-kit\index.cjs:52751:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_DROP_INDEX_FK',
  errno: 1553,
  sql: 'DROP INDEX `guild_members_teams_guild_member_id_guild_members_id_fk` ON `guild_members_teams`;',
  sqlState: 'HY000',
  sqlMessage: "Cannot drop index 'guild_members_teams_guild_member_id_guild_members_id_fk': needed in a foreign key constraint"       
}
```

I made a simple project to try to re-create it, once set up the `schema.ts`, I just execute:
```txt
npx drizzle-kit generate:mysql
npx drizzle-kit push:mysql
npx drizzle-kit push:mysql // Error here
```
The double push is just an example, usually I would make changes to the schema, regenerate it then push again and it triggers the error.

**Comment by AndriiSherman** [comment]
👀

**Comment by AndriiSherman** [comment]
found an issue, fixing

**Comment by AndriiSherman** [comment]
@AlessioDP just fixed it in `drizzle-kit@0.19.7`

**Comment by AlessioDP** [comment]
Yes it works, thanks!

**Comment by 205g0** [comment]
Now, a `drizzle-kit introspect:mysql` forgets the comma after the the generated ...`primaryKey(table.id)` line, check line 6 in following example:
```ts
export const users = mysqlTable("users", {
        ...
},
(table) => {
	return {
		usersId: primaryKey(table.id)
		email: unique("email").on(table.email),
	}
});
```

**Comment by moh682** [comment]
I'm experiencing the same issue now.
